# -*- coding: utf-8 -*-
"""dataloader.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRtuwe83lflserYb-IttZWPFysta7ew0
"""

def  get_dataloader(is_train, cuda):
      transform = transforms.Compose([transforms.RandomHorizontalFlip(),
                                 transforms.ToTensor(),
                                 transforms.Normalize(0.4914, 0.4822, 0.4465), (0.5, 0.5, 0.5)])
      dataloader_args = dict(shuffle=True, batch_size=128, num_workers=2, pin_memory=True) if cuda else dict(shuffle=True, batch_size=16)

      dataset = torchvision.datasets.CIFAR10(root='./data', train=is_train, download=True, transform=transform)
      dataloader = torch.utils.data.DataLoader(dataset, **dataloader_args)
      return dataloader





